<?php

namespace NB\MainBundle\Repository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends \Doctrine\ORM\EntityRepository
{
    public function ListeVilles(){

        $queryBuilder = $this
            ->createQueryBuilder('v')
            ->Where('v.isActive = :active')
            ->orderBy('v.nom', 'ASC')
            ->setParameters(array(  'active' => true));
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        // $results = $results[;


        // var_dump($results['booked']); exit;
        return $results;
    }

    public function findByName($name){

        $queryBuilder = $this
            ->createQueryBuilder('v')
            ->where('v.nom = :nom')
            ->andWhere('v.isActive = :active')
            ->orderBy('v.nom', 'ASC')
            ->setParameters(array(  'active' => true, 'nom' => $name));
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        // $results = $results[;


        //dump($results[0]); exit;
        return $results[0];


    }
}
