<?php

namespace NB\MainBundle\Repository;

/**
 * VoyagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyagesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAxes($source, $destination){

        $queryBuilder = $this
            ->createQueryBuilder('v')
            ->join('v.axes', 'ax')
            ->join('v.compagnie', 'co')
            ->addSelect('co')
            ->addSelect('ax')
            ->Where('ax.source = :src')
            ->andWhere('ax.destination =  :dest')
            ->orderBy('v.prix', 'ASC')
            ->setParameters(array( 'dest' => $destination, 'src' => $source, ));
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        // $results = $results[;


        //dump($results); exit;
        return $results;
    }
}
